# Generated by Django 5.2.6 on 2025-10-04 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.IntegerField()),
                ('moneda', models.CharField(default='UYU', max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('hobbies', 'Hobbies'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('regalos', 'Regalos'), ('estudio', 'Estudio'), ('transporte', 'Transporte'), ('otros', 'Otros gastos')], max_length=20)),
                ('date_movimiento', models.DateField()),
                ('date_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.IntegerField()),
                ('moneda', models.CharField(default='UYU', max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('sueldo', 'Sueldo / mesada'), ('regalo', 'Regalos'), ('otro', 'Otros ingresos')], max_length=20)),
                ('date_movimiento', models.DateField()),
                ('date_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
