# Generated by Django 5.2.6 on 2025-10-04 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('date_evento', models.DateField()),
                ('monto', models.IntegerField()),
                ('moneda', models.CharField(default='UYU', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('date_creacion', models.DateTimeField(auto_now_add=True)),
                ('date_cierre', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
