# Generated by Django 5.2.6 on 2025-10-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='titulo',
        ),
    ]
